### ISSUE TITLE
Number of points for annotation

### ISSUE THREAD

**Issue by abdou31** [luigivieira/Facial-Landmarks-Annotation-Tool#13]
Hello , 
I want to know is there a relationship between the number of points and the convolutional neural network?
what can be the number of points that CNN-facial landmarks accept for training and for testing .
For exemple in this picture , i have 10 points : ( 5 for right iris and 5 for left iris )
![image](https://user-images.githubusercontent.com/19480228/58405696-55720280-8068-11e9-8fb8-30cc33fe7701.png)
What is the maximal number of landmarks that can i using for annotation iris region?
is it depends on you tool or on the convolutional neural network created?
Thanks

**Comment by luigivieira** [comment]
Hello. How are things?
To my knowledge there is no relationship between the points and a convolution neural network. In fact, if you are using a convolution neural network and deep learning, usually you don't have to bother getting any landmarks because you do not need to extract the features: they will be obtained by the deep neural network directly from the raw values of pixels, in its initial layers during training...

Usually you annotate facial images when you are employing a different approach, that require you to extract features from the annotated landmarks (commonly geometric features like distances between eyes, eyebrows to nose tip, etc; ore texture features obtained with filters in the frequency domain).

**Comment by abdou31** [comment]
You don't understand me , the result that i want is iris detected with landmarks like the picture that i send .
That is the project that i worked on.
For the first time,  i used ibug dataset that contains( 300VW and 300W dataset , Helen dataset ) , it annotated with 68 landmarks on the face. and 
I trained this dataset and i get good results , so my object for now is trained dataset of face annotated to iris landmarks.
I hope that you understand what i mean, i will ask the author of CNN-Facial Landmarks what should i change to make the project train my own dataset.

**Comment by luigivieira** [comment]
I am sorry, but I do not know anything about a CNN-Facial Landmarks tool. You should talk to their creators. :)

**Comment by abdou31** [comment]
Okey Thanks

**Comment by abdou31** [comment]
I didn't know why i pts file like this , the space between in some lines is > 1 
Do you have any idea?
I ask about this beacause is give me errors while i try i generate .json files using extract_face_from_ibug.py from pts files created using Facial annotation tool 
So for exemple in this file :  

![image](https://user-images.githubusercontent.com/19480228/58466585-393e9600-813a-11e9-981d-3e6e822832f5.png)

Why it writed 317.85 not 317.850 ? how can i fix that?

**Comment by luigivieira** [comment]
1) Spaces are just spaces, and in this case they were probably used to make the alignment of the rightmost column prettier. Anyway, spaces shouldn't mean anything to the parser you are using (if you are not using one but building your own, you shouldn't - there are plenty of yaml parses around).
2) The reason is because the rightmost 0 is not significant. Again, this shouldn't mean anything to you. If you are writing your own parser based on column positions, you are doing it wrong. First of all, use an existing parser; and if you really want to write your own parser, cope with these differences.

**Comment by abdou31** [comment]
Problem fixed after changing line in the code that generate json files from .pts files
i mean : 
+ pts_tools.py
