### ISSUE TITLE
68-landmarks

### ISSUE THREAD

**Issue by rclim-11** [luigivieira/Facial-Landmarks-Annotation-Tool#4]
Hi, I was wondering if it's possible to configure the tool to annotate 68 landmarks instead of 66?

**Comment by luigivieira** [comment]
Hi. Yes, it is. You just create the 66 landmarks you want to. There are menu and button actions for creating and deleting landmarks. But if you meant to have the "automatic" annotation to find only 66 landmarks instead of 68, that is not currently possible because of the external tool used (CSIRO Face Analysis SDK). But if you have any other detector that provides 66 landmarks you can fork the project and create your own integration with that external tool.

Cheers,
